create table customer (id bigint not null auto_increment, address_line1 varchar(255), city varchar(255), country varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), phone_number varchar(15), reg_date date, user_name varchar(25), zipcode varchar(10), primary key (id)) engine=InnoDB;create table category (id bigint not null auto_increment, description longtext, primary key (id)) engine=InnoDB;
create table customer (id bigint not null auto_increment, address varchar(255), city varchar(255), country varchar(255), email varchar(255), first_name varchar(255), last_name varchar(255), phone_number varchar(15), zipcode varchar(10), primary key (id)) engine=InnoDB;
create table order_product (order_id bigint not null, product_id bigint not null) engine=InnoDB;
create table orders (id bigint not null auto_increment, date_ordered date, order_number integer, product_quantity integer, status varchar(255), total_price float, customer_id bigint, primary key (id)) engine=InnoDB;
create table payment (id bigint not null auto_increment, card_name varchar(255), card_number varchar(255), expire_date date, security_code integer, primary key (id)) engine=InnoDB;
create table privilege (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table product (id bigint not null auto_increment, brand varchar(255), description longtext, image longblob, in_stock integer, name varchar(255), price float, category_id bigint, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, role varchar(255), primary key (id)) engine=InnoDB;
create table roles_privileges (role_id bigint not null, privilege_id bigint not null) engine=InnoDB;
create table shopping_cart (id bigint not null auto_increment, quantity integer, subtotal_price float, product_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email varchar(255), first_name varchar(255), last_name varchar(255), password varchar(255), reg_date date, user_name varchar(25), customer_id bigint, primary key (id)) engine=InnoDB;
create table users_roles (user_id bigint not null, role_id bigint not null) engine=InnoDB;
alter table order_product add constraint FKhnfgqyjx3i80qoymrssls3kno foreign key (product_id) references product (id);
alter table order_product add constraint FKl5mnj9n0di7k1v90yxnthkc73 foreign key (order_id) references orders (id);
alter table orders add constraint FK624gtjin3po807j3vix093tlf foreign key (customer_id) references customer (id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (id);
alter table roles_privileges add constraint FK5yjwxw2gvfyu76j3rgqwo685u foreign key (privilege_id) references privilege (id);
alter table roles_privileges add constraint FK9h2vewsqh8luhfq71xokh4who foreign key (role_id) references role (id);
alter table shopping_cart add constraint FKerqg5bwr2tdlwabwdn7r4n2xo foreign key (product_id) references product (id);
alter table shopping_cart add constraint FK254qp5akhuaaj9n5co4jww3fk foreign key (user_id) references user (id);
alter table user add constraint FKdptx0i3ky01svofwjytq5iry0 foreign key (customer_id) references customer (id);
alter table users_roles add constraint FKt4v0rrweyk393bdgt107vdx0x foreign key (role_id) references role (id);
alter table users_roles add constraint FKgd3iendaoyh04b95ykqise6qh foreign key (user_id) references user (id);
